---
- name: Ensure privoxy package is present
  tags:
    - privoxy
  community.general.homebrew:
    name: privoxy
    state: present
    update_homebrew: false
    upgrade_all: false

- name: Ensure privoxy configuration is managed
  tags:
    - privoxy
  ansible.builtin.template:
    dest: "{{ privoxy_confdir }}/config"
    mode: '0640'
    src: config.j2
  notify:
    - Restart privoxy
...
