---
- name: Ensure privoxy package is present
  tags:
    - privoxy
  community.general.homebrew_cask:
    name: privoxy
    state: present
    update_homebrew: false
    upgrade_all: false

- name: Ensure privoxy configurations are present
  tags:
    - privoxy
  ansible.builtin.template:
    dest: "{{ privoxy_confdir }}/config"
    mode: 0640
    src: config.j2
  notify:
    - restart privoxy
...
