---
- name: Ensure rectangle package is managed
  tags:
    - rectangle
  community.general.homebrew_cask:
    name: "{{ rectangle_package }}"
    state: "{{ rectangle_state }}"
    update_homebrew: false
    upgrade_all: false

- name: Ensure rectangle defaults are managed
  tags:
    - rectangle
  community.general.osx_defaults:
    array_add: "{{ _default.array_add | d(omit) }}"
    domain: "{{ rectangle_domain }}"
    host: "{{ _default.host | d(omit) }}"
    key: "{{ _default.key }}"
    state: "{{ _default.state | d('present') }}"
    type: "{{ _default.type | d('string') }}"
    value: "{{ _default.value | d(omit) }}"
  loop: "{{ rectangle_defaults }}"
  loop_control:
    label: "{{ _default.key | d(none) }}"
    loop_var: _default
  when:
    - _default.key is defined
    - _default.value is defined or
      _default.state | d('present') != 'present'
...
