---
- name: Converge
  hosts: all
  roles:
    - role: homebrew_services_info
      homebrew_services_info_name: []
      tags:
        - molecule-idempotence-notest

    - role: homebrew
      tags:
        - molecule-idempotence-notest

    - homebrew_services_info
...
