---
authors:
  - Taylor Kimball (https://github.com/tkimball83)
build_ignore:
  - .gitignore
description: A collection of macos roles
dependencies:
  community.general: 10.3.1
documentation: https://github.com/linuxhq/ansible-collection-macos/blob/main/README.md
homepage: https://www.linuxhq.org
issues: https://github.com/linuxhq/ansible-collection-macos/issues
license:
  - GPL-3.0-or-later
name: macos
namespace: linuxhq
readme: README.md
repository: https://github.com/linuxhq/ansible-collection-macos
tags:
  - application
  - macos
  - tools
version: 1.0.5
...
