---
- name: Ensure irssi state is valid
  tags:
    - irssi
  ansible.builtin.fail:
    msg: irssi_state must be 'present' or 'absent'.
  when:
    - irssi_state not in ['present', 'absent']

- name: Ensure irssi package is managed
  tags:
    - irssi
  community.general.homebrew:
    name: irssi
    state: "{{ irssi_state }}"
    update_homebrew: false
    upgrade_all: false

- name: Ensure irssi present tasks are included
  tags:
    - irssi
  ansible.builtin.include_tasks:
    apply:
      tags:
        - irssi
    file: present.yml
  when:
    - irssi_state == 'present'

- name: Ensure irssi absent tasks are included
  tags:
    - irssi
  ansible.builtin.include_tasks:
    apply:
      tags:
        - irssi
    file: absent.yml
  when:
    - irssi_state == 'absent'
...
