---
dependencies: []
galaxy_info:
  role_name: rclone
  author: Taylor Kimball
  description: A command-line program to manage files on cloud storage
  license: GPLv3
  min_ansible_version: 2.15.0
  platforms:
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloud
    - macos
    - rclone
    - storage
...
