---
- name: Ensure liquidprompt package is present
  tags:
    - liquidprompt
  community.general.homebrew:
    name: liquidprompt
    state: present
    update_homebrew: false
    upgrade_all: false

- name: Ensure liquidprompt configuration is present
  tags:
    - liquidprompt
  ansible.builtin.template:
    dest: "{{ liquidprompt_dst }}/.liquidpromptrc"
    mode: 0644
    src: liquidpromptrc.j2
...
