---
- name: Ensure rclone package is present
  tags:
    - rclone
  community.general.homebrew:
    name: rclone
    state: present
    update_homebrew: false
    upgrade_all: false

- name: Ensure rclone configuration path is present
  tags:
    - rclone
  ansible.builtin.file:
    mode: '0755'
    path: "{{ rclone_path_conf | dirname }}"
    state: directory
  when:
    - rclone_conf | length > 0

- name: Ensure rclone configuration file is present
  tags:
    - rclone
  ansible.builtin.template:
    dest: "{{ rclone_path_conf }}"
    mode: '0600'
    src: rclone.conf.j2
  when:
    - rclone_conf | length > 0

- name: Ensure rclone property list directory is present
  tags:
    - rclone
  ansible.builtin.file:
    mode: '0755'
    path: "{{ ansible_facts.env.HOME }}/Library/LaunchAgents"
    state: directory
  when:
    - rclone_mounts | length > 0

- name: Ensure rclone property list mountpoint is present
  tags:
    - rclone
  ansible.builtin.file:
    mode: '0755'
    path: "{{ _mount.mountpoint }}"
    state: directory
  loop: "{{ rclone_mounts }}"
  loop_control:
    label: "{{ _mount.mountpoint | d(none) }}"
    loop_var: _mount
  when:
    - _mount.mountpoint is defined

- name: Ensure rclone property list file is present
  tags:
    - rclone
  ansible.builtin.template:
    dest: "{{ ansible_facts.env.HOME }}/Library/LaunchAgents/{{ _mount.name }}.plist"
    mode: '0644'
    src: rclone.plist.j2
  register: __rclone_plist
  loop: "{{ rclone_mounts }}"
  loop_control:
    label: "{{ _mount.name | d(none) }}"
    loop_var: _mount
  notify:
    - Reload rclone agents
  when:
    - _mount.name is defined
    - _mount.remote is defined
    - _mount.mountpoint is defined

- name: Ensure rclone service information is gathered
  tags:
    - rclone
  linuxhq.macos.launchd_info:
    name:
      "{{ rclone_mounts |
          selectattr('name', 'defined') |
          map(attribute='name') |
          list }}"
  register: __rclone_launchd
  when:
    - rclone_mounts | length > 0

- name: Ensure rclone property list agents are started
  tags:
    - rclone
  community.general.launchd:
    enabled: true
    name: "{{ _mount.name }}"
    state: started
  loop: "{{ rclone_mounts }}"
  loop_control:
    label: "{{ _mount.name | d(none) }}"
    loop_var: _mount
  when:
    - _mount.name is defined
    - _mount.name not in
        __rclone_launchd.services |
        d([]) |
        selectattr('running') |
        map(attribute='label') |
        list
    - _mount.remote is defined
    - _mount.mountpoint is defined
    - not ansible_check_mode
...
