---
allow_duplicates: true
dependencies: []
galaxy_info:
  role_name: homebrew_services_info
  author: Taylor Kimball
  description: Gather information about Homebrew services
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - homebrew
    - info
    - macos
    - services
...
