---
- name: Ensure codex package is managed
  tags:
    - codex
  community.general.homebrew_cask:
    name: "{{ codex_package }}"
    state: "{{ codex_state }}"
    update_homebrew: false
    upgrade_all: false

- name: Ensure codex tasks are included
  tags:
    - codex
  ansible.builtin.include_tasks:
    apply:
      tags:
        - codex
    file: include.yml
  when:
    - codex_state not in ['absent', 'removed', 'uninstalled']
...
