---
shell_proxy_file: "{{ lookup('env', 'HOME') }}/.bash_proxies"
shell_proxy_ftp: false
shell_proxy_ftp_hostname: localhost
shell_proxy_ftp_password: null
shell_proxy_ftp_port: 8080
shell_proxy_ftp_protocol: http
shell_proxy_ftp_username: null
shell_proxy_http: false
shell_proxy_http_hostname: localhost
shell_proxy_http_password: null
shell_proxy_http_port: 8080
shell_proxy_http_protocol: http
shell_proxy_http_username: null
shell_proxy_https: false
shell_proxy_https_hostname: localhost
shell_proxy_https_password: null
shell_proxy_https_port: 8080
shell_proxy_https_protocol: http
shell_proxy_https_username: null
shell_proxy_noproxy:
  - 127.0.0.1
  - localhost
...
