---
- name: Ensure homebrew is updated
  tags:
    - homebrew
  community.general.homebrew:
    update_homebrew: true
  when:
    - homebrew_update | bool

- name: Ensure all homebrew packages are upgraded
  tags:
    - homebrew
  community.general.homebrew:
    upgrade_all: true
    upgrade_options: "{{ homebrew_upgrade_options }}"
  when:
    - homebrew_upgrade | bool

- name: Ensure homebrew packages are managed
  tags:
    - homebrew
  community.general.homebrew:
    force_formula: "{{ _package.force_formula | d(false) }}"
    install_options: "{{ _package.install_options | d(omit) }}"
    name: "{{ _package.name }}"
    path: "{{ homebrew_path or omit }}"
    state: "{{ _package.state | d('present') }}"
  loop: "{{ homebrew_list }}"
  loop_control:
    label: "{{ _package.name | d(none) }}"
    loop_var: _package
  when:
    - _package.name is defined
...
