---
dependencies: []
galaxy_info:
  role_name: monitorcontrol
  author: Taylor Kimball
  description: Control your external monitor brightness, contrast or volume
  license: GPLv3
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - macos
    - monitorcontrol
...
