---
- name: Verify
  hosts: all
  tasks:
    - name: Ensure appzapper application status is gathered
      tags:
        - appzapper
      ansible.builtin.stat:
        path: /Applications/AppZapper.app
      register: __appzapper_present_stat

    - name: Ensure appzapper application is present
      tags:
        - appzapper
      ansible.builtin.assert:
        that:
          - __appzapper_present_stat.stat.exists

    - name: Ensure appzapper role is included with an absent state
      tags:
        - appzapper
      ansible.builtin.include_role:
        name: appzapper
      vars:
        appzapper_state: absent

    - name: Ensure appzapper application status is gathered after removal
      tags:
        - appzapper
      ansible.builtin.stat:
        path: /Applications/AppZapper.app
      register: __appzapper_absent_stat

    - name: Ensure appzapper application is absent
      tags:
        - appzapper
      ansible.builtin.assert:
        that:
          - not __appzapper_absent_stat.stat.exists
...
