---
- name: Ensure proton vpn package is present
  tags:
    - proton_vpn
  community.general.homebrew_cask:
    name: "{{ proton_vpn_package }}"
    state: present
    update_homebrew: false
    upgrade_all: false

- name: Ensure proton vpn defaults are managed
  tags:
    - proton_vpn
  community.general.osx_defaults:
    array_add: "{{ _default.array_add | d(omit) }}"
    domain: "{{ proton_vpn_domain }}"
    host: "{{ _default.host | d(omit) }}"
    key: "{{ _default.key }}"
    state: present
    type: "{{ _default.type | d('string') }}"
    value: "{{ _default.value }}"
  loop: "{{ proton_vpn_defaults }}"
  loop_control:
    label: "{{ _default.key | d(none) }}"
    loop_var: _default
  when:
    - _default.key is defined
    - _default.value is defined
...
