---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant
  provider:
    name: tart

platforms:
  - name: tahoe
    hostname: false
    memory: 8192
    cpus: 4
    provider_options:
      disk: 60
      image: ghcr.io/cirruslabs/macos-tahoe-base:latest
      name: tahoe
    config_options:
      synced_folder: false
      ssh.username: admin
      ssh.password: admin
      vm.boot_timeout: 900

provisioner:
  name: ansible
  env:
    ANSIBLE_ACTION_WARNINGS: false
    ANSIBLE_DEPRECATION_WARNINGS: false
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        rclone_conf:
          - name: public
            type: http
            url: https://pub.rclone.org

        rclone_mounts:
          - name: org.linuxhq.rclone.public
            remote: 'public:'
            mountpoint: "{{ ansible_facts.env.HOME }}/Volumes/Public"
            flags:
              - --read-only

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
