---
- name: Restart privoxy
  tags:
    - privoxy
  community.general.homebrew_services:
    name: privoxy
    state: restarted
  when:
    - privoxy_state == 'present'
    - not ansible_check_mode
...
