---
dependencies: []
galaxy_info:
  role_name: privoxy
  author: Taylor Kimball
  description: A non-caching web proxy
  license: GPLv3
  min_ansible_version: 2.14.0
  platforms:
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - macos
    - privoxy
...
